//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_300_TFA_application {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint TRANSMIT_COMMAND_CHECK {
            get {
                return ((uint)(this["TRANSMIT_COMMAND_CHECK"]));
            }
            set {
                this["TRANSMIT_COMMAND_CHECK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QUEUE_FAIL {
            get {
                return ((int)(this["QUEUE_FAIL"]));
            }
            set {
                this["QUEUE_FAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint QUEUE_PASS {
            get {
                return ((uint)(this["QUEUE_PASS"]));
            }
            set {
                this["QUEUE_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint QUEUE_FREE {
            get {
                return ((uint)(this["QUEUE_FREE"]));
            }
            set {
                this["QUEUE_FREE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int _ANS_MESSAGE_ACK_RECIEVED {
            get {
                return ((int)(this["_ANS_MESSAGE_ACK_RECIEVED"]));
            }
            set {
                this["_ANS_MESSAGE_ACK_RECIEVED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int _ANS_MESSAGE_NACK_RECIEVED {
            get {
                return ((int)(this["_ANS_MESSAGE_NACK_RECIEVED"]));
            }
            set {
                this["_ANS_MESSAGE_NACK_RECIEVED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _ANS_MESSAGE_ACK {
            get {
                return ((int)(this["_ANS_MESSAGE_ACK"]));
            }
            set {
                this["_ANS_MESSAGE_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int _ANS_MESSAGE_NACK {
            get {
                return ((int)(this["_ANS_MESSAGE_NACK"]));
            }
            set {
                this["_ANS_MESSAGE_NACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACK")]
        public string _MESSAGE_ACK {
            get {
                return ((string)(this["_MESSAGE_ACK"]));
            }
            set {
                this["_MESSAGE_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NACK")]
        public string _MESSAGE_NACK {
            get {
                return ((string)(this["_MESSAGE_NACK"]));
            }
            set {
                this["_MESSAGE_NACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WARNING")]
        public string _MESSAGE_WAR {
            get {
                return ((string)(this["_MESSAGE_WAR"]));
            }
            set {
                this["_MESSAGE_WAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COMMUNICATION ERROR")]
        public string _MESSAGE_COM_ERR {
            get {
                return ((string)(this["_MESSAGE_COM_ERR"]));
            }
            set {
                this["_MESSAGE_COM_ERR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int _COMMUNICATION_DIR_PORT1 {
            get {
                return ((int)(this["_COMMUNICATION_DIR_PORT1"]));
            }
            set {
                this["_COMMUNICATION_DIR_PORT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int _COMMUNICATION_DIR_PORT2 {
            get {
                return ((int)(this["_COMMUNICATION_DIR_PORT2"]));
            }
            set {
                this["_COMMUNICATION_DIR_PORT2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int _COMMUNICATION_DIR_PORT3 {
            get {
                return ((int)(this["_COMMUNICATION_DIR_PORT3"]));
            }
            set {
                this["_COMMUNICATION_DIR_PORT3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public char _ID_DEBUG {
            get {
                return ((char)(this["_ID_DEBUG"]));
            }
            set {
                this["_ID_DEBUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public char _ID_TFA {
            get {
                return ((char)(this["_ID_TFA"]));
            }
            set {
                this["_ID_TFA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public char _ID_MT {
            get {
                return ((char)(this["_ID_MT"]));
            }
            set {
                this["_ID_MT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(">")]
        public char _SER_START_SIGN {
            get {
                return ((char)(this["_SER_START_SIGN"]));
            }
            set {
                this["_SER_START_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string _COM_PORT1_REC_TRANS {
            get {
                return ((string)(this["_COM_PORT1_REC_TRANS"]));
            }
            set {
                this["_COM_PORT1_REC_TRANS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string _COM_PORT2_REC_TRANS {
            get {
                return ((string)(this["_COM_PORT2_REC_TRANS"]));
            }
            set {
                this["_COM_PORT2_REC_TRANS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TRANSMIT_SLOT_FREE {
            get {
                return ((int)(this["TRANSMIT_SLOT_FREE"]));
            }
            set {
                this["TRANSMIT_SLOT_FREE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int _TIME_FOR_ACK {
            get {
                return ((int)(this["_TIME_FOR_ACK"]));
            }
            set {
                this["_TIME_FOR_ACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYNCHRONUS_TRANSMITT {
            get {
                return ((bool)(this["SYNCHRONUS_TRANSMITT"]));
            }
            set {
                this["SYNCHRONUS_TRANSMITT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SYNCHRO_SEND_WAIT {
            get {
                return ((int)(this["SYNCHRO_SEND_WAIT"]));
            }
            set {
                this["SYNCHRO_SEND_WAIT"] = value;
            }
        }
    }
}
